"""add_highlights_table

Revision ID: 18eb8791cf3c
Revises: c5a1d18de36e
Create Date: 2026-07-30 14:56:59.411952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18eb8791cf3c'
down_revision: Union[str, None] = 'c5a1d18de36e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('position_start', sa.Integer(), nullable=True),
    sa.Column('position_end', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highlights_id'), 'highlights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_highlights_id'), table_name='highlights')
    op.drop_table('highlights')
    # ### end Alembic commands ###
